import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Grand Sapphire Resorts - Twilight in the Hills
        "deep-forest": "#122E22",
        "twilight-navy": "#0D1B2E",
        "warm-ivory": "#F8F5EC",
        "antique-gold": "#C9A227",
        "amber-glow": "#F0A94E",
        // Material tokens from DESIGN.md
        primary: "#00190F",
        "on-primary": "#FFFFFF",
        "primary-container": "#122E22",
        "on-primary-container": "#799787",
        secondary: "#755B00",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#FED255",
        "on-secondary-container": "#735A00",
        tertiary: "#211100",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#3D2300",
        "on-tertiary-container": "#C3822A",
        surface: "#FCF9F0",
        "surface-dim": "#DADAD1",
        "surface-bright": "#FCF9F0",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F6F3EA",
        "surface-container": "#F1EEE5",
        "surface-container-high": "#EBE8DF",
        "surface-container-highest": "#E5E2DA",
        "on-surface": "#1C1C17",
        "on-surface-variant": "#424844",
        "inverse-surface": "#31312B",
        "inverse-on-surface": "#F4F1E8",
        outline: "#727974",
        "outline-variant": "#C2C8C2",
        "surface-tint": "#486456",
        background: "#FCF9F0",
        "on-background": "#1C1C17",
        "surface-variant": "#E5E2DA",
        error: "#BA1A1A",
        "on-error": "#FFFFFF",
        "error-container": "#FFDAD6",
        "on-error-container": "#93000A",
      },
      fontFamily: {
        brand: ["var(--font-brand)", "Storm Wraith", "Cormorant Garamond", "serif"],
        headline: ["var(--font-cormorant-garamond)", "Cormorant Garamond", "serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "hero-desktop": ["3.5rem", { lineHeight: "1.1", fontWeight: "600" }],
        "hero-mobile": ["2.5rem", { lineHeight: "1.2", fontWeight: "600" }],
        "section-title": ["2.25rem", { lineHeight: "1.2", fontWeight: "600" }],
        "section-title-lg": ["3rem", { lineHeight: "1.1", fontWeight: "600" }],
        "card-title": ["1.5rem", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["1rem", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["1.125rem", { lineHeight: "1.7", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["0.75rem", { lineHeight: "1.4", fontWeight: "500", letterSpacing: "0.08em" }],
      },
      borderRadius: {
        "chip": "4px",
        "card": "12px",
        "hero": "24px",
        "input": "10px",
        "button": "10px",
        "luxury": "16px",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        "2xl": "120px",
        "3xl": "160px",
        "max-width": "1280px",
      },
      boxShadow: {
        "card-hover": "0 12px 32px rgba(18, 46, 34, 0.1)",
        "warm": "0 8px 24px rgba(18, 46, 34, 0.08)",
        "hero": "0 24px 80px rgba(13, 27, 46, 0.35)",
        "luxury": "0 20px 60px rgba(201, 162, 39, 0.15)",
        "glass": "0 8px 32px rgba(0, 0, 0, 0.08)",
      },
      transitionDuration: {
        "fast": "150ms",
        "normal": "250ms",
        "slow": "400ms",
        "luxury": "600ms",
      },
      transitionTimingFunction: {
        "ease-out": "ease-out",
        "ease-in": "ease-in",
        "ease-luxury": "cubic-bezier(0.22, 1, 0.36, 1)",
        "spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
        "elegant": "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
      },
      maxWidth: {
        "content": "1280px",
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [],
};
export default config;